#
# Counter!
#
	ldi 34
    wrw R1 # start at zero
    # R1 is the counter variable
_loop_1    rdw R1
    wrw DISP_BASE

    addi 1
    wrw R1 # increment R1 by one
    ldi 0

    ## Delay
    ldi 25000 # 1 ms delay (25k * 2 cycles / 50000 kHz = 1 ms)
_delay_1 nop
    bneqi _delay_1
    nop
    nop
    ## end delay
    beqi _loop_1




#finish program by jumping back to boot ROM
	ldi 0
	beqi PROG_ROM
	nop
    nop

