# START

start nop

# Acquire operands and operation
##
## R15 - Signal op or operator
## R14 - Hundreds op
## R13 - Tens op
## R12 - Ones op

# jump to acquire_key
ak1 ldi ret1
    wrw R10
    bneqi acquire_key
ret1 nop

    ldi 0x01
    wrw GPO_BASE

# if(R1 == KEY_PLUS)
    ldi KEY_PLUS
    wrw R2 # R2 <- key code for compare
    rdw R1
    xor R2 # key code XOR comp key code - 0 if equal
    beqi handle_plus # skip if
# if(R1 == KEY_MINUS)

    ldi 0x03
    wrw GPO_BASE
    ldi KEY_MINUS
    wrw R2 # R2 <- key code for compare
    rdw R1
    xor R2 # key code XOR comp key code - 0 if equal
    beqi handle_minus # skip if
# else ignore_keycode
# jump to acquire_key

    ldi 0x07
    wrw GPO_BASE
    ldi 0
    beqi ak1

# handle +
handle_plus ldi 10 # 10 mean plus
    wrw R15
    
    ldi 0x0F
    wrw GPO_BASE
    
    ldi 0
    beqi end_signal_handles # skip minus handler
# handle -
handle_minus ldi 11 # 11 means minus
    wrw R15

    ldi 0x1F
    wrw GPO_BASE

end_signal_handles

    rdw R15
    wrw DISP_BASE

stop ldi 0
beqi stop
# number keycodes
# 0 | 70
# 1 | 69
# 2 | 72
# 3 | 7A
# 4 | 6B
# 5 | 73
# 6 | 74
# 7 | 6C
# 8 | 75
# 9 | 7D

# operations keycodes
# + | 79
# - | 7B
# * | 7C
# / | 4A


# Do operation



# Print result

# loop to start
        ldi 0
        beqi start
        nop
        nop

# (never) finish program by jumping back to boot ROM
finish	nop
        ldi 0
        beqi PROG_ROM
        nop
        nop

## acquire_key routine
acquire_key nop
        # wait for new key press
        rdw PS2_BASE
        wrw R1 # store the ps2 module output unchanged
        ## RA >> 8 to get new key bit (maybe optimizable with a loop)
        shft 1 #1
        shft 1 #2
        shft 1 #3
        shft 1 #4
        shft 1 #5
        shft 1 #6
        shft 1 #7
        shft 1 #8
        ##
        beqi acquire_key # loop
        nop
        nop

        #take out the valid bit from the ps2 output
        ldi 0x0FF # mask for 8 last bits
        wrw R2 # R2 <- mask
        rdw R1 # RA <- R1
        and R2 # R1 AND mask
        wrw R1 # R1 <- key code. R1 now only contains the key code

        ldi 0
        beqi R10 # return
## end acquire_key - key code is in R1
