#
# Counter!
#
loop_1  rdw PS2_BASE
        wrw R1 # store the ps2 module output unchanged

        #take out the valid bit from the ps2 output
        ldi 0x0FF # mask for 8 last bits
        wrw R2 # R2 <- mask
        rdw R1 # RA <- R1
        and R2 # R1 AND mask
        wrw R1 # R1 <- key code. R1 now only contains the key code

## end acquire_key - key code is in R1
    rdw R1 # get the key code
    wrw DISP_BASE
    ldi 0
    beqi loop_1




#finish program by jumping back to boot ROM
	ldi 0
	beqi PROG_ROM
	nop
    nop

